eliminate GCC 16.1.0 compile error
Fix the following compile error:

    In file included from /usr/include/c++/16.1.1/map:65,
                     from /home/sergiu/Projects/g2o/g2o/core/hyper_graph.h:34,
                     from /home/sergiu/Projects/g2o/g2o/core/optimizable_graph.h:39,
                     from /home/sergiu/Projects/g2o/g2o/core/base_edge.h:36,
                     from /home/sergiu/Projects/g2o/g2o/core/base_binary_edge.h:33,
                     from /home/sergiu/Projects/g2o/g2o/types/sba/types_six_dof_expmap.h:32,
                     from /home/sergiu/Projects/ORB_SLAM/src/Optimizer.cc:21:
    /usr/include/c++/16.1.1/bits/stl_map.h: In instantiation of ‘class std::map<ORB_SLAM::KeyFrame*, g2o::eigen_requires_32_bytes_alignment::Sim3, std::less<ORB_SLAM::KeyFrame*>, Eigen::aligned_allocator<std::pair<ORB_SLAM::KeyFrame*, g2o::eigen_requires_32_bytes_alignment::Sim3> > >’:
    /home/sergiu/Projects/ORB_SLAM/src/Optimizer.cc:581:25:   required from here
      581 |         if(CorrectedSim3.count(pKF))
          |                         ^
    /usr/include/c++/16.1.1/bits/stl_map.h:129:71: error: static assertion failed: std::map must have the same value_type as its allocator
      129 |       static_assert(is_same<typename _Alloc::value_type, value_type>::value,
          |                                                                       ^~~~~
      • ‘std::integral_constant<bool, false>::value’ evaluates to false